title: European Youth Parliament Croatia
author: eyp.hr
email: info@eyp.hr
description: >-
  Our mission is to inspire youth and support them in developing their roles in 
  society through debates and international dialogue. In cooperation with 39 national 
  EYP branches, we open the door to hundreds of young people every year.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
